# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42246257c2bc1e7ed88df1a3dac416ed9cbc0c56c73ddc5b148490cdae62e2ac057e664a7b0f9e1d747c13efb06bb69a2cc29cb3c85827ed8f905ed9a360099d

test:
  secret_key_base: 60609a6da702f79541269a3499a9f8f16f5079eaf15decbcbe0141faee3900b3bb692938727387f16d7ecfcedc16ba7e30b3235b8cdc60f33f959d9d71e764b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
